INSERT INTO db_schema.user_info (id_user, id_google, spotify_token)
VALUES (1, 'google-id-1', null),
       (2, 'google-id-2', null),
       (3, 'google-id-3', null),
       (4, 'google-id-3', null),
       (5, 'google-id-3', null),
       (6, 'google-id-3', null),
       (7, 'google-id-3', null),
       (8, 'google-id-3', null),
       (9, 'google-id-3', null),
       (10, 'google-id-3', null),
       (11, 'google-id-3', null),
       (12, 'google-id-3', null),
       (13, 'google-id-3', null),
       (14, 'google-id-3', null),
       (15, 'google-id-3', null),
       (16, 'google-id-3', null),
       (17, 'google-id-3', null),
       (18, 'google-id-3', null),
       (19, 'google-id-3', null),
       (20, 'google-id-3', null);